import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Dongle&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className="antialiased w-full overflow-x-hidden bg-gradient-to-r from-[#FF6F91] via-[#FFD43B] to-[#4FB1FF]"
        style={{ fontFamily: "'Dongle', sans-serif" }}
      >
        <div className="max-w-[480px] mx-auto bg-white min-h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
