export const questions = [
  {
    id: 1,
    text: "물회를 먹을 땐 어떤 스타일이 좋아요?",
    optionA: "얼음육수에 말아 시원하게 ❄️",
    optionB: "고추장 양념에 새콤하게 비벼먹는 게 좋아 🌶️",
    resultA: "속초파",
    resultB: "포항파",
    score: 1.2,
    bgGradient: "from-blue-100 to-cyan-50",
    accentColor: "bg-blue-500",
    decorColor: "text-blue-400",
  },
  {
    id: 2,
    text: "한입 먹었을 때 끌리는 맛은?",
    optionA: "새콤달콤하고 균형 잡힌 맛 🍋",
    optionB: "자극 있고 칼칼한 맛 🔥",
    resultA: "강릉파",
    resultB: "포항파",
    score: 1.15,
    bgGradient: "from-orange-100 to-yellow-50",
    accentColor: "bg-orange-500",
    decorColor: "text-orange-400",
  },
  {
    id: 3,
    text: "식사로 먹을 때 더 좋은 건?",
    optionA: "된장국처럼 구수하고 든든한 스타일 🍲",
    optionB: "차갑고 산뜻한 스타일 💧",
    resultA: "제주된장파",
    resultB: "남해파",
    score: 1.1,
    bgGradient: "from-green-100 to-teal-50",
    accentColor: "bg-green-500",
    decorColor: "text-green-400",
  },
  {
    id: 4,
    text: "바다의 향이 강한 쪽이 좋아요?",
    optionA: "소금기 있는 짭조름한 맛 🌊",
    optionB: "멍게·전복 향이 진한 해산물 맛 🐚",
    resultA: "자리물회파",
    resultB: "남해파",
    score: 1.05,
    bgGradient: "from-teal-100 to-blue-50",
    accentColor: "bg-teal-500",
    decorColor: "text-teal-400",
  },
  {
    id: 5,
    text: "양념 색은 어떤 게 더 식욕을 돋워요?",
    optionA: "투명하고 맑은 육수 💧",
    optionB: "붉은 양념이 진한 비빔형 ❤️‍🔥",
    resultA: "자리물회파",
    resultB: "포항파",
    score: 1.05,
    bgGradient: "from-red-100 to-pink-50",
    accentColor: "bg-red-500",
    decorColor: "text-red-400",
  },
  {
    id: 6,
    text: "밥과 함께 먹는다면?",
    optionA: "밥 말아 한 끼로 든든하게 🍚",
    optionB: "회만 시원하게 즐기고 싶어 ❄️",
    resultA: "제주된장파",
    resultB: "강릉파",
    score: 1,
    bgGradient: "from-yellow-100 to-amber-50",
    accentColor: "bg-yellow-500",
    decorColor: "text-yellow-400",
  },
  {
    id: 7,
    text: "물회를 고를 때 중요하게 보는 건?",
    optionA: "식감(탱탱한 회) 🐟",
    optionB: "향(멍게·전복 풍미) 🐚",
    resultA: "속초파",
    resultB: "남해파",
    score: 0.95,
    bgGradient: "from-purple-100 to-indigo-50",
    accentColor: "bg-purple-500",
    decorColor: "text-purple-400",
  },
  {
    id: 8,
    text: "더운 여름, 물회를 찾는 이유는?",
    optionA: "시원하고 단짠한 맛이 생각나서 🍧",
    optionB: "바다 본연의 맛이 그리워서 🌊",
    resultA: "속초파",
    resultB: "자리물회파",
    score: 0.95,
    bgGradient: "from-cyan-100 to-sky-50",
    accentColor: "bg-cyan-500",
    decorColor: "text-cyan-400",
  },
  {
    id: 9,
    text: "물회를 먹는다면 누구와?",
    optionA: "친구들과 시끌벅적하게 🍻",
    optionB: "혼자 조용히 즐기며 여유롭게 🌾",
    resultA: "강릉파",
    resultB: "제주된장파",
    score: 0.95,
    bgGradient: "from-pink-100 to-rose-50",
    accentColor: "bg-pink-500",
    decorColor: "text-pink-400",
  },
];